### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by egel557** [spitzc32/Caroline#5]
The following codes don't go entirely through the analyzer:
```
INT count
count = 1 // The analyzer doesn't continue after this line

FOR count TO 100 BY 1
    PRINT(count)
ENDLOOP
````

```
bool flag = TRUE // The analyzer doesn't continue after this line

WHILE flag
    PRINT(count)
ENDLOOP
```

The following code doesn't produce a parse tree:
```
INT count
```
But this code does:
```
INT count
PRINT(count)
```

**Comment by spitzc32** [comment]
bug #1 cant replicate.
bug #2 fixed
bug #3 prob with is_prog() not fixed. Unidentified issue.

**Comment by spitzc32** [comment]
done with pull request of fixing end of file bug
